shallow_clone: true

os:
  - Visual Studio 2019

environment:
  matrix:
  - TOOLSET: vs2017
  - TOOLSET: vs2019

configuration:
  - Debug
  - Release

install:
  tools\bin\windows\genie %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bx.sln
