language: cpp

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

  - os: osx
    osx_image: xcode7.3

  - os: osx
    osx_image: xcode8.3

  - os: osx
    osx_image: xcode9.2

  - os: linux
    dist: trusty
    addons:
      apt:
        packages: clang-4.0
        sources:
           - ubuntu-toolchain-r-test
           - llvm-toolchain-trusty-4.0
    env:
      - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

  - os: linux
    dist: trusty
    addons:
      apt:
        packages: g++-6
        sources:
           - ubuntu-toolchain-r-test
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  - os: linux
    dist: trusty
    addons:
      apt:
        packages: clang-5.0
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
          key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

#   - os: linux
#     dist: trusty
#     addons:
#       apt:
#         packages: clang-6.0
#         sources:
#         - ubuntu-toolchain-r-test
#         - llvm-toolchain-trusty
#     env:
#       - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"


before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      brew update;
      brew outdated cmake || brew upgrade cmake;
    fi

  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      eval "${MATRIX_EVAL}";
    fi

before_script:
  - mkdir build 
  - cd build

script:
  - ${CXX} --version
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release -- -j2
  - ctest -V -C Release
