#define MODEL_MATRIX_BINDING 10
#define ENTITY_INPUT_LOCATION 10
#define ENTITY_INPUT_BINDING 0

#define VTX_POSITION_BINDING 1
#define VTX_NORMAL_BINDING 2
#define VTX_TANGENT_BINDING 3
#define VTX_BITANGENT_BINDING 4
#define VTX_UV0_BINDING 5
#define VTX_LIGHTMAP_BINDING 6